/** Catálogo OBS-003 — prefijo runtime: obs.action.<area>.<action> */
export const ACTION_EVENTS = {
  system: {
    bootstrap: "obs.action.system.bootstrap",
    degraded: "obs.action.system.degraded",
  },
  workspace: {
    viewChange: "obs.action.workspace.viewChange",
    explorerToggle: "obs.action.workspace.explorerToggle",
    rightPanelToggle: "obs.action.workspace.rightPanelToggle",
    settingsOpen: "obs.action.workspace.settingsOpen",
    versionsOpen: "obs.action.workspace.versionsOpen",
  },
  project: {
    open: "obs.action.project.open",
    close: "obs.action.project.close",
    create: "obs.action.project.create",
  },
  explorer: {
    select: "obs.action.explorer.select",
    viewMode: "obs.action.explorer.viewMode",
    expand: "obs.action.explorer.expand",
    inlineCreate: "obs.action.explorer.inlineCreate",
    inlineCommit: "obs.action.explorer.inlineCommit",
    inlineCancel: "obs.action.explorer.inlineCancel",
    dnd: "obs.action.explorer.dnd",
    contextMenu: "obs.action.explorer.contextMenu",
    searchQuery: "obs.action.explorer.search.query",
  },
  editor: {
    tabOpen: "obs.action.editor.tabOpen",
    tabClose: "obs.action.editor.tabClose",
    tabSwitch: "obs.action.editor.tabSwitch",
    save: "obs.action.editor.save",
    saveAll: "obs.action.editor.saveAll",
    dirtyDiffToggle: "obs.action.editor.dirtyDiffToggle",
    unsavedDialog: "obs.action.editor.unsavedDialog",
    sidePanelTab: "obs.action.editor.sidePanelTab",
    insertTimeTag: "obs.action.editor.insertTimeTag",
    externalReload: "obs.action.editor.externalReload",
    wikiLinkOpen: "obs.action.editor.wikiLink.open",
    focus: "obs.action.editor.focus",
  },
  layout: {
    explorerResize: "obs.action.layout.explorer.resize",
    panelResize: "obs.action.layout.panel.resize",
  },
  map: {
    open: "obs.action.map.open",
    resolveInitial: "obs.action.map.resolveInitial",
    select: "obs.action.map.select",
    setOpenPreference: "obs.action.map.setOpenPreference",
    setDefaultOnOpen: "obs.action.map.setDefaultOnOpen",
    create: "obs.action.map.create",
    expandCanvas: "obs.action.map.expandCanvas",
    cropCanvas: "obs.action.map.cropCanvas",
    setViewMode: "obs.action.map.setViewMode",
    drawStroke: "obs.action.map.drawStroke",
    saveDrawing: "obs.action.map.saveDrawing",
    brushChange: "obs.action.map.brushChange",
    colorChange: "obs.action.map.colorChange",
    toolChange: "obs.action.map.toolChange",
    undo: "obs.action.map.undo",
    redo: "obs.action.map.redo",
  },
  graph: {
    nodeOpen: "obs.action.graph.nodeOpen",
  },
  consistency: {
    issueNavigate: "obs.action.consistency.issueNavigate",
  },
  entity: {
    open: "obs.action.entity.open",
  },
  settings: {
    open: "obs.action.settings.open",
    close: "obs.action.settings.close",
    theme: "obs.action.settings.theme",
    locale: "obs.action.settings.locale",
    autosave: "obs.action.settings.autosave",
    closeProject: "obs.action.settings.closeProject",
    calendar: "obs.action.settings.calendar",
  },
  timeline: {
    filterToggle: "obs.action.timeline.filterToggle",
    chipClick: "obs.action.timeline.chipClick",
    chipHover: "obs.action.timeline.chipHover",
    connectorToggle: "obs.action.timeline.connectorToggle",
    openCalendar: "obs.action.timeline.openCalendar",
  },
  calendar: {
    panelEditToggle: "obs.action.calendar.panel.editToggle",
    sectionToggle: "obs.action.calendar.section.toggle",
    monthsEditMode: "obs.action.calendar.months.editMode",
    monthAdd: "obs.action.calendar.month.add",
    monthRemove: "obs.action.calendar.month.remove",
    monthReorder: "obs.action.calendar.month.reorder",
    monthDaysChange: "obs.action.calendar.month.daysChange",
    openMonth: "obs.action.calendar.openMonth",
    closeMonth: "obs.action.calendar.closeMonth",
    yearChange: "obs.action.calendar.yearChange",
    topBarYearChange: "obs.action.calendar.topBar.yearChange",
    draftSave: "obs.action.calendar.draft.save",
    draftDiscard: "obs.action.calendar.draft.discard",
    draftUnsavedDialog: "obs.action.calendar.draft.unsavedDialog",
    deleteCalendar: "obs.action.calendar.deleteCalendar",
    deleteCalendarChoice: "obs.action.calendar.deleteCalendar.choice",
    monthDeleteDialog: "obs.action.calendar.monthDelete.dialog",
    seasonEditMode: "obs.action.calendar.season.editMode",
    specialYearEditMode: "obs.action.calendar.specialYear.editMode",
    daySelect: "obs.action.calendar.day.select",
    monthShift: "obs.action.calendar.month.shift",
  },
  launcher: {
    createOpen: "obs.action.launcher.createOpen",
    recentRemove: "obs.action.launcher.recentRemove",
  },
} as const;
